### ISSUE TITLE
Create a database at startup

### ISSUE THREAD

**Issue by fungiboletus** [apache/couchdb-docker#142]
The documentation says

> Please note that CouchDB no longer autocreates system databases for you, as it is not known at startup time if this is a single-node or clustered CouchDB installation.

Could it be possible to add back the possibility to autocreate the database when the container is not used in a cluster ? It could be a simple `if` on an optional environment variable.

**Comment by wohali** [comment]
This would be better served as a CouchDB enhancement, not a Docker enhancement. Moving the issue.

**Comment by happilymarrieddad** [comment]
@fungiboletus @wohali 

https://github.com/apache/couchdb-docker/pull/148

**Comment by florianb** [comment]
For all restless souls having the same problem, we just redefined the dockerfile `CMD`:

```
docker run couchdb:latest sh -c "/opt/couchdb/bin/couchdb & { sleep 3 ; curl -X PUT http://127.0.0.1:5986/_users ; curl -X PUT http://127.0.0.1:5986/_replicator ; curl -X PUT http://127.0.0.1:5986/_global_changes ; fg ; }"
```

`&` puts CouchDb in the background and runs subsequent commands in the foreground, `{}` couples the inner commands without invoking a subshell, `;` runs the commands sequentially, `sleep 3` waits 3 seconds (to let relax a bit), `curl`creates the missing database and `fg` pulls the CouchDb job to the foreground again.

:couch_and_lamp: 

---

Our original `.gitlab-ci.yml`-service:

```yaml
services:
  - name: couchdb:latest
    command: ["sh", "-c", "/opt/couchdb/bin/couchdb & { sleep 3 ; curl -X PUT http://127.0.0.1:5986/_users ; curl -X PUT http://127.0.0.1:5986/_replicator ; curl -X PUT http://127.0.0.1:5986/_global_changes ; fg ; }"]
```
