### ISSUE TITLE
touching docker.ini on startup does not respond well to a readonly filesystem

### ISSUE THREAD

**Issue by guest20** [apache/couchdb-docker#183]
Overwriting `local.d/docker.ini` from `k8s` causes the couch container to go into `CrashLoopBackOff` because `touch: cannot touch '/opt/couchdb/etc/local.d/docker.ini': Read-only file system`

## Expected Behavior

I'd expect to just be able to mount my own  `docker.ini` over the top of the one in the container so I can skip the setup wizard (in my case I only `n=1`)

## Current Behavior

`CrashLoopBackOff` because couchdb crashes when it attempts to touch `docker.ini`

## Steps to Reproduce (for bugs)

The `single-node.ini` seen here came from clicking "single node cluster" in the ui, and then grabbing the config from the running contgainer. 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-ini
data:
  single-node.ini: |
    [admins]
    admin = -pbkdf2-████████████████████████
    [couchdb]
    uuid = ████████████████████████████████
    [couch_httpd_auth]
    secret = ████████████████████████████████
    [chttpd]
    bind_address = 0.0.0.0
    port = 5984
    [log]
    level = debug
    writer = stderr
    [cluster]
    n = 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  replicas: 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3.0.1
        ports:
        - containerPort: 5984
        envFrom:
          - configMapRef:
              name: couchdb-config
        volumeMounts:
          - name: config-volume
            mountPath:  /opt/couchdb/etc/local.d/docker.ini
            subPath: single-node.ini
      volumes:
        - name: config-volume
          configMap:
            name: couchdb-ini
            items:
            - key: single-node.ini
              path: single-node.ini 
```
1. `kubectl apply -f ...`
1, `kubectl get pods `

## Context
my cluster was built via `k3s`, and runs `fluxcd` to apply changes to my manifests - I think i've managed to pare it down.

## Your Environment

* Version used: 3.0.1, from dockerhub 
* Operating System and version (desktop or mobile): `Linux dave 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux `
* 
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3+k3s1", GitCommit:"96653e8d86b74a1f73eadf09d4edc44778c2f8dd", GitTreeState:"clean", BuildDate:"2020-06-01T16:47:11Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3+k3s1", GitCommit:"96653e8d86b74a1f73eadf09d4edc44778c2f8dd", GitTreeState:"clean", BuildDate:"2020-06-01T16:47:11Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}      
```
