### ISSUE TITLE
Container exits with no log messages if configuration file is provided

### ISSUE THREAD

**Issue by jnordberg** [apache/couchdb-docker#204]
## Expected Behavior

The container should start using the config files provided.

## Current Behavior

The container exits with code 1 and no log messages.

## Possible Solution

Make configs in /etc/local.d/* readable before running couchdb in the docker entrypoint

## Steps to Reproduce (for bugs)

stack.yml

```yml
services:
  couch1:
    image: couchdb:3.1
    configs:
      - source: admins
        target: /opt/couchdb/etc/local.d/10-admins.ini
configs:
  admins:
    file: ./admins.ini
```

admins.ini

```ini
[admins]
admin = -pbkdf2-2006b7b27f5f3624c54e37f5126f3db2bd515a0f,ac2121044edb47438573c80764ba7dc5,10000
```

## Context

This bug prevents me from launching a cluster of couchdb instances in my docker swarm without setting the password as plaintext in the environment variables.

Workaround can be found here: https://github.com/apache/couchdb-docker/issues/73#issuecomment-766179802

## Your Environment

Docker 20.10.8
