### ISSUE TITLE
couchdb:3.2.2 crashes when NODENAME env var is set

### ISSUE THREAD

**Issue by nevans** [apache/couchdb-docker#236]
## Expected Behavior

When a simple docker executor with the `couchdb:3.2.2` image is added to .circleci/config.yml, the container starts successfully and serves requests until the job completes.

The container is created with the following output, or similar:
```
couchdb:3.2.2:
  using image couchdb@sha256:2f75fc7e2cd0b10c6dbd20bec00df82d0b961ea4441b56efcb3cdcb36e4ed794
  pull stats: download 52.96MiB in 502ms (105.5MiB/s), extract 52.93MiB in 1.464s (36.14MiB/s)
  time to create container: 13ms
```

After which, there should be a green check-mark next to "Container: couchdb":3.2.2 in the running job.  This converts to a grey cancelled icon when the job completes:

![Good build screenshot](https://user-images.githubusercontent.com/6142/226989740-2e1c8777-f7ad-4d1c-b706-00c7a6007598.png)

## Current Behavior

The container exits with an error code and waiting for it will timeout.

The container is created with the following output _(n.b: the updated sha256 checksum)_:
```
couchdb:3.2.2:
  using image couchdb@sha256:dda616310897b4498ba5ec232d2e97b70e1d8e52841b3c2dfc46f649fb5a4d62
  pull stats: download 52.06MiB in 507ms (102.6MiB/s), extract 52.02MiB in 1.474s (35.29MiB/s)
  time to create container: 456ms
```

![Screenshot 2023-03-22 at 13-29-41](https://user-images.githubusercontent.com/6142/226990352-4b3bcf1f-c850-4627-b457-4299a362c966.png)

## Possible Solution

The workaround is to use an older image by SHA or by tag.  Then everything works just fine again.

## Steps to Reproduce (for bugs)

The following CircleCI configuration might trigger the bug.  I haven't tested this _exact_ config.yml; mine is about 400 lines longer.  I'm _hoping_ this is enough and it captures the bug, but I might have simplified too much.  Please let me know if you need more information, and I'll reproduce it in a public repo and CircleCI project.

```yml
version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: ubuntu
        environment:
          COUCHDB_USER: appname
          COUCHDB_PASSWORD: circleci-qwertyzxcvb
      - image: couchdb:3.2.2
        environment:
          COUCHDB_USER: appname
          COUCHDB_PASSWORD: circleci-qwertyzxcvb
          NODENAME: appname
  steps:
    - docker/install_dockerize
    - run:
      command: |
        dockerize -wait tcp://localhost:5984
        echo "docker responded"
```

## Context

This started only two days ago, around the time that the new images were pushed.

Could something have changed environment variables, such that the ones I'm using are causing this?  Alternatively, I see that gosu was removed and setpriv is used, could that be related?
