### ISSUE TITLE
Can you please specify the steps for setting couchdb clustering in windows, right now I have single node setup , I would like to make it 2 node cluster.

### ISSUE THREAD

**Issue by Jyothishb4** [apache/couchdb-docker#74]
Can you please specify the steps for setting couchdb clustering in windows, right now I have single node setup , I would like to make it 2 node cluster.

**Comment by endyjasmi** [comment]
@Jyothishb4 Hello, here is the way I setup my cluster. I'm going to assume that you are running in standalone docker engine and not docker swarm.

1. `docker-compose  up -d` the `docker-compose.yml` attached below.
2. Login with username: `couchdb` and password: `password`.
3. Go to `http://localhost:5984/_utils` and configure cluster.
4. Setup the field based on;
```
username: couchdb
password: password
bind_address: 0.0.0.0
port: 5984
cluster_n: 3

add note 1:
remote_host: couchdb-1.docker.com
bind_address: 0.0.0.0
port: 5984

add note 2:
remote_host: couchdb-1.docker.com
bind_address: 0.0.0.0
port: 5984
```
5. Click the final complete button once (there are no visual feedback)
6. And you are done, you can access which ever node (localhost:5984/15984/25984).

### docker-compose.yml
```yml
version: "3.5"

networks:
  network:

services:
  server-0:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb-0.docker.com
    image: couchdb:2.1.1
    networks:
      network:
        aliases:
          - couchdb-0.docker.com
    ports:
      - "5984:5984"
      - "5986:5986"
    volumes:
      - "volume-0:/opt/couchdb/data"
  server-1:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb-1.docker.com
    image: couchdb:2.1.1
    networks:
      network:
        aliases:
          - couchdb-1.docker.com
    ports:
      - "15984:5984"
      - "15986:5986"
    volumes:
      - "volume-1:/opt/couchdb/data"
  server-2:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb-2.docker.com
    image: couchdb:2.1.1
    networks:
      network:
        aliases:
          - couchdb-2.docker.com
    ports:
      - "25984:5984"
      - "25986:5986"
    volumes:
      - "volume-2:/opt/couchdb/data"

volumes:
  volume-0:
  volume-1:
  volume-2:
```

**Comment by wohali** [comment]
The official documentation on CouchDB in a cluster is here:

http://docs.couchdb.org/en/latest/cluster/setup.html#cluster-setup

The above instructions apply to any method of deployment, not just using the Docker container.

CouchDB recommends a minimum of a 3-node cluster deployment, not 2.

@kocolosk is working on a helm file for kubernetes deployment.

**Comment by Jyothishb4** [comment]
@wohali ,

Do we need to setup Erlang ? . I don't have curl or Erlang setup in my environment, Only thing I have done is created a standalone instance and I need to add one more node to this setup. Can you please help me ?

Thanks,
Jyothish B

**Comment by wohali** [comment]
For advice with CouchDB I recommend our IRC #couchdb channel on Freenode ,the matching Slack channel, or the mailing list at user@couchdb.apache.org.

**Comment by Jyothishb4** [comment]
Hi @wohali 

I have copied curl to couchdb server and tried to add the node using couchdb documentation but I am getting one error,

curl --ssl-no-revoke -X POST -H "Content-Type: application/json" https://admin:password@xxxxx:6984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"x.x.x.x", "username": "admin", "password":"password", "node_count":"2"}'


curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
curl: (6) Could not resolve host: enable_cluster,
curl: (3) Port number ended with '.'
curl: (6) Could not resolve host: username
curl: (6) Could not resolve host: admin,
curl: (3) Port number ended with 'w'
curl: (3) [globbing] unmatched close brace/bracket in column 13

**Comment by wohali** [comment]
Known issue: https://github.com/apache/couchdb/issues/783

**Comment by regnete** [comment]
@endyjasmi: Thank you for providing a working example. 

I had to made some adjustments to get it working with couchdb 3.1.0. I wan't to share this for others running in problems when setting up a couchdb 3 cluster with docker-compose. Hope, this is usefull for anybody out there.

1. explicitly set an erlang cookie on each node via ENV var. Cookie value must be equal on all nodes. Otherwise you will get connection issues between nodes (e.g. "Connection attempt from disallowed node")
```
    server-0:
         environment:
              ERL_FLAGS: "-setcookie brumbrum"
```

2. Mount the `/opt/couchdb/etc/local.d` directory as volume to have it persisted over `docker-compose down` and `docker-compose up -d`. Otherwise each node will write new given COUCHDB_PASSWORD's hash on every `docker-compose up -d` to /opt/couchdb/etc/local.d/docker.ini. In consequence the hashes for the admin passwords differ between nodes and you are ending up with connection issues between the nodes (e.g. 'no_majority').

```
server-0:
    volumes:
        - "data-couch-0:/opt/couchdb/data"
        - "cfg-couch-0:/opt/couchdb/etc/local.d"
```

```
volumes:
  data-couch-0:
  cfg-couch-0:
  data-couch-1:
  cfg-couch-1:
  data-couch-2:
  cfg-couch-2:
```

3. No need to map Port  5886 to the public


Here is the complete content for a docker-compose.yml:

```
version: "3.5"

networks:
  network:

services:
  server-0:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb-0.docker.com
      ERL_FLAGS: "-setcookie brumbrum"
    image: couchdb:3
    networks:
      network:
        aliases:
          - couchdb-0.docker.com
    ports:
      - "5984:5984"
    volumes:
      - "data-couch-0:/opt/couchdb/data"
      - "cfg-couch-0:/opt/couchdb/etc/local.d"
  server-1:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb-1.docker.com
      ERL_FLAGS: "-setcookie brumbrum"
    image: couchdb:3
    networks:
      network:
        aliases:
          - couchdb-1.docker.com
    ports:
      - "15984:5984"
    volumes:
      - "data-couch-1:/opt/couchdb/data"
      - "cfg-couch-1:/opt/couchdb/etc/local.d"
  server-2:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb-2.docker.com
      ERL_FLAGS: "-setcookie brumbrum"
    image: couchdb:3
    networks:
      network:
        aliases:
          - couchdb-2.docker.com
    ports:
      - "25984:5984"
    volumes:
      - "data-couch-2:/opt/couchdb/data"
      - "cfg-couch-2:/opt/couchdb/etc/local.d"

volumes:
  data-couch-0:
  cfg-couch-0:
  data-couch-1:
  cfg-couch-1:
  data-couch-2:
  cfg-couch-2:
```
