### ISSUE TITLE
Can't initiate cluster setup using referenced API

### ISSUE THREAD

**Issue by IIIRADIII** [apache/couchdb-docker#77]
Can't initiate cluster setup using API and UI with accordance to docs http://docs.couchdb.org/en/2.1.1/cluster/setup.html

## Expected Behavior
I am trying to create cluster, for starters manually, using  API or web interface.
My compose file for swarm
```
version: '3.6'
services:
  cluster:
    image: apache/couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    networks:
      my_nw:
        aliases:
          - couchdb
    ports:
      - target: 5984
        published: 5984
        mode: host
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
networks:
  my_nw:
    external: true
```
OR single command for standalone container
```
 docker run -d -p 5984:5984  --env COUCHDB_USER=admin --env COUCHDB_PASSWORD=admin apache/couchdb
```
I expect to successfully initiate cluster setup with request
`curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"admin", "node_count":"3"}'
`

## Current Behavior
Getting error in response to provided request
`
{"error":"bad_request","reason":"Cluster is already enabled"}
`
The same error appears when I am trying to do it manually in web interface.(On network tab of Chrome Developer tools I can see the same error in response to provided request)

## Possible Solution
Unfortunately, no ideas

## Steps to Reproduce (for bugs)
1. Run on any Linux host with Docker.
`
 docker run -d -p 5984:5984  --env COUCHDB_USER=admin --env COUCHDB_PASSWORD=admin apache/couchdb
`
2. Execute request with curl on this machine 
`
curl -X POST -H "Content-Type: application/json" http://admin:admin@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"admin", "node_count":"2"}'
`

## Context
I am trying to make docker compose stack for Docker Swarm 

## Your Environment
* Version used: Docker version 18.03.1-ce, image apache/couchdb:2.1.1 (latest at the moment)
* Browser Name and version:  Chrome Version 66.0.3359.139
* Operating System and version (desktop or mobile): Tested on Windows 10 and RHEL7
* Link to your project: None
