### ISSUE TITLE
bind_address problem?

### ISSUE THREAD

**Issue by librehost** [apache/couchdb-docker#99]
In the file: couchdb-docker/2.2.0/10-docker-default.ini you use: bind_address = any but in terms of http://docs.couchdb.org/en/stable/config/http.html this is not a valid option. Also when i verify installation this setting seems to break replication until i set it to 0.0.0.0.

## Environment
Couch 2.2 behind reverseproxy

**Comment by wohali** [comment]
Hi @librehost , this file is unchanged from 2.1.1, see

https://github.com/apache/couchdb-docker/blob/aa4ee2d3cbdb17b41e0adff9e23241be47b23441/2.1.1/local.ini

Are you using our entrypoint shell script? That script sets the correct values.

**Comment by librehost** [comment]
Hi @wohali i think the shell script does not set them:

https://github.com/apache/couchdb-docker/blob/f429c1ccf22fe8cf7717383462fbf2f56e6d0301/2.2.0/docker-entrypoint.sh

**Comment by librehost** [comment]
In the script for 1.7.2 there is something like that but not for 2.2.0 or do i miss something?

**Comment by wohali** [comment]
@librehost CouchDB 2.2.0 supports "any" as a value, see:

https://github.com/apache/couchdb/blob/master/src/chttpd/src/chttpd.erl#L116

and

https://github.com/apache/couchdb/blob/master/src/couch/src/couch_httpd.erl#L97

If it didn't, our Travis tests on this repository would fail, and they pass.

Something else must be wrong in your setup. I'm closing this ticket as invalid, but I'm happy to help diagnose your problem further in this thread.

**Comment by elavaud** [comment]
Similar issue here

On Fauxton verify installation fails unless I bind 0.0.0.0 during setup. 
And even then the verify still fails, but this time at the last step "replication".
(which I wonder if this is normal because it is anyway a single node setup with no replication configured yet).

Docker-compose on Ubuntu 16.04 (Loki 4.1):

```
version: "3.3"
services:
  couch:
    image: couchdb:2.2.0
    env_file: .env
    ports:
      - "5984:5984"
    volumes:
      - type: volume
        source: couch_data
        target: /opt/couchdb/data

volumes:
  couch_data:
```
